version: '3.9'

services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - backnet
  #   depends_on:
  #     - backend

  redis:
    # image: arm64v8/redis -- for macos
    image: "redis:alpine"
    networks:
    - backnet
    expose:
      - 6379

  db:
    # image: arm64v8/mysql -- for macos
    image: mysql:8.0.20
    restart: "no"
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - mysql-local:/var/lib/mysql
    env_file:
      - ./.docker.env
    networks:
      - backnet

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.hot
    restart: "no"
    ports:
      - "5001:5000"
    expose:
      - 5000
    command:
      flask --app src.init_app --debug run --host 0.0.0.0
    depends_on:
      - db
      - redis
    env_file:
      - ./.docker.env
    volumes:
      - ./backend/src:/app/src
    networks:
      - backnet
  
  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    restart: "no"
    networks:
      - backnet
    command: celery -A src.init_celery worker -l info -E
    # command: ls -la src
    depends_on:
          - redis
    ports:
      - "6666:5555"
    expose:
      - 5555
    env_file:
      - ./.docker.env
    volumes:
      - ./worker/src:/app/src
      - stanzavolume:/app/stanza_resources
      
networks:
  backnet:

volumes:
  stanzavolume:
  mysql-local: