CREATE DATABASE IF NOT EXISTS LANGUAGEAPPDB;

USE LANGUAGEAPPDB;

DROP USER IF EXISTS 'user'@'%';
CREATE USER 'user'@'%' IDENTIFIED BY 'password';

GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;